version: '2'

services:

  refgpec:
    container_name: refgpec
    image: node:6.9.1
    working_dir: /app
    volumes:
      - .:/app
    tty: true
    stdin_open: true  # to be able to use CTRL+C to stop the debug
    environment:
      NODE_ENV: "development"
      DEBUG: ${DEBUG}
    ports:
      - 8080:8080
    command: npm run dev

  refgpec-db:
    container_name: refgpec-db
    image: postgres:9.6.3
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d/ # to generate automatically table and insert after docker's initialization
    environment:
      POSTGRES_DB: "refgpec"
      POSTGRES_USER: "refgpec"
      POSTGRES_PASSWORD: "gpecsecret"
      PGDATA: "/var/lib/postgresql/data"
    ports:
      - 5432:5432

  refgpec-db-admin:
    container_name: refgpec-db-admin
    image: fenglc/pgadmin4:1.6
    environment:
      DEFAULT_USER: "gpec@inist.fr"
      DEFAULT_PASSWORD: "gpecsecret"
    ports:
      - 5050:5050
    links:
      - refgpec-db

  refgpec-api:
    container_name: refgpec-api
    image: postgrest/postgrest:v0.4.3.0
    ports:
      - 3000:3000
    links:
      - refgpec-db:db
    environment:
      PGRST_DB_URI: postgres://refgpec:gpecsecret@refgpec-db:5432/refgpec
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: web_anon
      PGRST_SERVER_PROXY_URI: http://127.0.0.1:3000/
