version: '2'

services:

  refgpec:
    container_name: refgpec
    image: nginx:1.13.3
    volumes:
      - ./refgpec/nginx.debug.conf:/etc/nginx/conf.d/default.conf
      - ./refgpec/logs/:/var/log/nginx
    links:
      - refgpec-cra
      - refgpec-api
    ports:
      - 8081:80

  refgpec-cra:
    container_name: refgpec-cra
    image: node:6.9.1
    working_dir: /app
    volumes:
      - ./refgpec:/app
    tty: true
    stdin_open: true  # to be able to use CTRL+C to stop the debug
    command: npm run start

  refgpec-db:
    container_name: refgpec-db
    image: postgres:9.6.3
    volumes:
      - ./refgpec-db/data/postgres:/var/lib/postgresql/data
      - ./refgpec-db/sql:/docker-entrypoint-initdb.d/ # to generate automatically table and insert after docker's initialization
    environment:
      POSTGRES_DB: "refgpec"
      POSTGRES_USER: "refgpec"
      POSTGRES_PASSWORD: "gpecsecret"
      PGDATA: "/var/lib/postgresql/data"
    ports:
      - 5432:5432

  refgpec-db-admin:
    container_name: refgpec-db-admin
    image: fenglc/pgadmin4:1.6
    environment:
      DEFAULT_USER: "gpec@inist.fr"
      DEFAULT_PASSWORD: "gpecsecret"
    ports:
      - 5050:5050
    links:
      - refgpec-db

  refgpec-api:
    container_name: refgpec-api
    image: postgrest/postgrest:v0.4.3.0
    ports:
      - 3000:3000
    links:
      - refgpec-db:db
    environment:
      PGRST_DB_URI: postgres://refgpec:gpecsecret@refgpec-db:5432/refgpec
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: web_anon
      PGRST_SERVER_PROXY_URI: http://127.0.0.1:3000/api/

