version: '2'

services:

  # RefGPEC frontend (ReactJS app)
  refgpec-front:
    container_name: refgpec-front
    build:
      context: ./refgpec-front
      args:
        - http_proxy
        - https_proxy
    image: inistcnrs/refgpec-front:1.1.1
    links:
      - refgpec-api
    ports:
      - 8081:80

  # RefGPEC API (PostgREST API)
  refgpec-api:
    container_name: refgpec-api
    build:
      context: ./refgpec-api
      args:
        - http_proxy
        - https_proxy
    image: inistcnrs/refgpec-api:1.1.1
    links:
      - refgpec-db:db
    environment:
      PGRST_DB_URI: postgres://refgpec:gpecsecret@refgpec-db:5432/refgpec
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: web_anon
      PGRST_SERVER_PROXY_URI: http://127.0.0.1:3000/api/

  # RefGPEC database (PostgreSQL database)
  refgpec-db:
    container_name: refgpec-db
    build:
      context: ./refgpec-db
      args:
        - http_proxy
        - https_proxy
    image: inistcnrs/refgpec-db:1.1.1
    volumes:
      - ./refgpec-db/data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "refgpec"
      POSTGRES_USER: "refgpec"
      POSTGRES_PASSWORD: "gpecsecret"
      PGDATA: "/var/lib/postgresql/data"

  # RefGPEC database admin backoffice (pgadmin4)
  refgpec-db-admin:
    container_name: refgpec-db-admin
    build:
      context: ./refgpec-db-admin
      args:
        - http_proxy
        - https_proxy
    image: inistcnrs/refgpec-db-admin:1.1.0
    environment:
      DEFAULT_USER: "gpec@inist.fr"
      DEFAULT_PASSWORD: "gpecsecret"
    ports:
      - 5050:5050
    links:
      - refgpec-db
